language: node_js
node_js:
  - 8
  - 9
  - 10
after_success:
  - npm run coverage
services:
  - mysql
env:
  global:
    - LOG_LEVEL=debug PORT=3001
    - ENCRYPTION_ALGORITHM=aes-256-ctr
    - ENCRYPTION_KEY=ab0d7bfd2f9f8e604275fca29fa1a803b7e3368ae3e49f90823f3064a5b5a3dc
    - SESSION_KEY=d58d68213c2d27f45715cc299f867cf8e1cc658f078046e144129f883ae923cc
    - SESSION_NAME=bm-ui-sess
    - SITE_HOST=http://localhost:3000
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=
    - DB_CONNECTION_LIMIT=5
