language: node_js
node_js:
  - 8
  - 9
  - 10
cache: npm
after_success:
  - npm run coverage
services:
  - mysql
env:
  global:
    - LOG_LEVEL=debug PORT=3001
    - ENCRYPTION_KEY=b097b390a68441cc3bb151dd0171f25c3aabc688c50eeb26dc5e13254b333911
    - SESSION_KEY=a73545a5f08d2906e39a4438014200303f9269f3ade9227525ffb141294f1b62
    - SESSION_NAME=bm-ui-sess
    - SITE_HOST=http://localhost:3000
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=
    - DB_CONNECTION_LIMIT=5
